### ISSUE TITLE
TypeError: Cannot read property 'data' of undefined error

### ISSUE THREAD

**Issue by pavel-R5** [sumcumo/cypress-testrail-reporter#6]
Hey @ma-jahn , sorry for bothering, but seem like I've found an issue.
When we add the configuration for cypress-testrail-reporter, but still have no cases linked(no [1] in names of the tests), we receive a `TypeError: Cannot read property 'data' of undefined` error when trying to run tests. 
Maybe adding come kind of an error catching to the reporter would be a nice idea? 
Cause for CI/CD this behavior gives you a failed run with no failed tests :disappointed: .

**Comment by ma-jahn** [comment]
Hi @pavel-R5 

.data is actually only used when processing responses from testrail.
Do you have any further details / logs to this issue?

i have also tested the reporter using a cypress report with multiple tests / suits but without any cases linked.
It just works fine.
Were there maybe some network issues?

**Comment by ma-jahn** [comment]
I've just release v1.4.0 with some maintenance / deps updates.

You'll also find the requested `reportFilename` config support :-)

Please let me know if this is working for you :v:

**Comment by pavel-R5** [comment]
Hello, @ma-jahn 

Here is part of the error log which contains the error mentioned earlier. Maybe that would help you.
May the "Field :name is not a valid string" message be a reason here?

```
Start Test Rail Export [
  [ 'Automation', 'R5C-954-Update-flex' ],
  './cypress/reports/html/index.json',
  false,
  [],
  []
]
Test results parsed []
Passed: [ 0 ]
Skipped: [ 0 ]
Failed: [ 0 ]
parsedTestResults [
  '{"analysis":{"passed":0,"failed":0,"skipped":0},"results":[{"file":"cypress/tests/Installation_Tests/1.09_FloatBase_Device_installation_page_tests.spec.js","cases":{}},{"file":"cypress/tests/Installation_Tests/1.09_FloatRover_Device_installation_page_tests.spec.js","cases":{}},{"file":"cypress/tests/Installation_Tests/1.09_Gateway_Device_installation_page_tests.spec.js","cases":{}},{"file":"cypress/tests/Installation_Tests/1.09_PivotMonitor_Device_installation_page_tests.spec.js","cases":{}},{"file":"cypress/tests/Installation_Tests/1.09_Scarecrow_Device_installation_page_tests.spec.js","cases":{}},{"file":"cypress/tests/Installation_Tests/1.09_Watermark_Device_installation_page_tests.spec.js","cases":{}},{"file":"cypress/tests/Installation_Tests/1.09_Flex_Device_installation_page_tests.spec.js","cases":{}}],"testRailCases":[]}'
]
cids [ [] ]
Add Run Automation,R5C-954-Update-flex [ [] ]
(node:14001) UnhandledPromiseRejectionWarning: Error: Field :name is not a valid string.
    at onError (/home/circleci/r5-click-aqa/node_modules/@sum.cumo/cypress-testrail-reporter/dist/reporter/index.js:80:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:14001) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:14001) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Posting Failed [
  TypeError: Cannot read property 'data' of undefined
      at onError (/home/circleci/r5-click-aqa/node_modules/@sum.cumo/cypress-testrail-reporter/dist/reporter/index.js:80:36)
]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tests@2.0.0 cypress:testrail-report: `cypress-testrail-reporter --name Automation --reportFilename ./cypress/reports/html/index.json --name R5C-954-Update-flex`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tests@2.0.0 cypress:testrail-report script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2021-06-16T14_14_17_734Z-debug.log
ERROR: "cypress:testrail-report" exited with 1.
```

P.S.: all tests were executed without failures.
